### ISSUE TITLE
Should AlphaPart() function include colYOB as an argument?

### ISSUE THREAD

**Issue by janaobsteter** [AlphaGenes/AlphaPart#2]
How do we determine in the AlphaPart() function which column contains the year of birth? Should we add this as an argument?

**Comment by gregorgorjanc** [comment]
It does!

https://github.com/AlphaGenes/AlphaPart/blob/37852a1a5740482bcd56f2ac8383ad416d3f455f/man/AlphaPart.Rd#L7 says

```
AlphaPart(x, pathNA, recode, unknown, sort, verbose, profile,
  printProfile, pedType, colId, colFid, colMid, colPath, colBV,
  colBy, center, scaleEBV)
```

You can of course also do it later as per https://github.com/AlphaGenes/AlphaPart/blob/37852a1a5740482bcd56f2ac8383ad416d3f455f/man/summary.AlphaPart.Rd#L7

```
\method{summary}{AlphaPart}(object, by, FUN, labelSum, subset,
  sums, cov,  ...)
```

does this help?

**Comment by janaobsteter** [comment]
Sorry, I must be blind or having a bad brain day. We can feed in `colId`, `colFid`, `colMid` , but not `colYOB` if I see correctly?

**Comment by gregorgorjanc** [comment]
`AlphaPart()` has `colBy` argument. Here is function definition from https://github.com/AlphaGenes/AlphaPart/blob/37852a1a5740482bcd56f2ac8383ad416d3f455f/R/AlphaPart.R#L155

```
AlphaPart <- function (x, pathNA=FALSE, recode=TRUE, unknown= NA,
                       sort=TRUE, verbose=1, profile=FALSE,
                       printProfile="end", pedType="IPP", colId=1,
                       colFid=2, colMid=3, colPath=4, colBV=5:ncol(x),
                       colBy=NULL, center = TRUE, 
                       scaleEBV = list()) {
```

**Comment by janaobsteter** [comment]
Ah, ok - I though that we also use the birth year for sorting the pedigree, but I see that that is done in another way (by `orderPed()` function). All good then!
